database:
  host: localhost
  user: CHANGETHIS
  password: CHANGETHIS
  database: CHANGETHIS
  tableprefix: tedisync
teamspeak:
  enabled: false
  login:
    host: 127.0.0.1
    virtual_server_id: 1
    query_username: CHANGETHIS
    query_password: CHANGETHIS
    query_displayname: CHANGETHIS
discord:
  enabled: false
  login_token: CHANGETHIS
  giveawaychannel: CHANGETHIS



