teamspeak:
  enabled: false
  login:
    host: 127.0.0.1
    port: 9987
    query_port: 10011
    query_username: CHANGETHIS
    query_password: CHANGETHIS
    query_displayname: CHANGETHIS
  database:
    host: localhost
    user: CHANGETHIS
    password: CHANGETHIS
    database: CHANGETHIS
    tableprefix: teamspeak
  oldDatabase:
    host: localhost
    user: CHANGETHIS
    password: CHANGETHIS
    database: CHANGETHIS
    tableprefix: teamspeak
  rankIDs:
    default: 10
    vip: 440
    veteran: 439
    creator: 303
    builder: 450
    buddy: 36
    staff: 26
    admin: 22
    owner: 379
  newbieGroup: 11
  ignoreGroups:
    - 201
  message: Du bist neu auf unserem TeamSpeak. Um dich freizuschalten gib !register <MinecraftName> ein und akzeptiere die anfrage in Minecraft.
discord:
  enabled: false
  login_token: CHANGETHIS
  serverID: CHANGETHIS
  giveawaychannel: CHANGETHIS
  registerchannel: CHANGETHIS
  invitelink: 'http://cubesi.de/discord'
  convert: false
  rankIDs:
    default: 1137641342382645308
    vip: 440
    veteran: 1137452248520204439
    creator: 303
    builder: 1137455331560136866
    buddy: 425669363891437568
    staff: 425000515106111488
    admin: 424999861155528734
    owner: 175993592769150977
  database:
    host: localhost
    user: CHANGETHIS
    password: CHANGETHIS
    database: CHANGETHIS
    tableprefix: discord



