teamspeak:
  enabled: false
  login:
    host: 127.0.0.1
    virtual_server_id: 1
    query_username: CHANGETHIS
    query_password: CHANGETHIS
    query_displayname: CHANGETHIS
  database:
    host: localhost
    user: CHANGETHIS
    password: CHANGETHIS
    database: CHANGETHIS
    tableprefix: teamspeak
  oldDatabase:
    host: localhost
    user: CHANGETHIS
    password: CHANGETHIS
    database: CHANGETHIS
    tableprefix: teamspeak
  rankIDs:
    default: 10
    vip: 440
    veteran: 439
    creator: 303
    builder: 450
    buddy: 36
    staff: 26
    admin: 22
    owner: 379
  newbieGroup: 11
  message: Du bist neu auf unserem TeamSpeak. Um dich freizuschalten gib !register <MinecraftName> ein und akzeptiere die anfrage in Minecraft.
discord:
  enabled: false
  login_token: CHANGETHIS
  giveawaychannel: CHANGETHIS
  registerchannel: CHANGETHIS
  invitelink: 'http://cubesi.de/discord'



